### ISSUE TITLE
Best Practices of Design Systems within HfLA & external organizations

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#423]
### Overview
This issue collates best practices of existing Design Systems both within HfLA and across external organizations. This would create the foundation to develop a logo and branding for a slide deck template for presentations and other components for the UI/UX CoP.

### Action Items

- [x] Review information & connect with Design Systems team of HfLA 
- [x] Review information & connect with Website team within HfLA
- [x] Review information & connect with TWE team of HFLA 
- [x] Review information from existing Guides within HfLA that deal with Design Systems 
- [x] Review existing best practices of design systems & material design from external organizations  
- [x] Collate & identify all the best examples that can be replicated within the UI/UX CoP 
- [x] Recruit a team of UI designers by creating an issue on UI/UX Design Open Roles
- [x] Contact admin regarding a new figma file for UI/UX CoP

### Resources/Instructions

**Resources gathered prior to completion of issue**
[Design Systems Repo: Design systems open to everyone in the Figma Community](https://www.designsystems.com)
[Material Design: Material 3 is the latest version of Google’s open-source design system](https://m3.material.io)
[Google Drive](https://drive.google.com/drive/folders/1nEGYRi6nrDbehRVZLf2_5D_IDJcwEDrU?usp=sharing)

**Comment by nguyen-jenn** [comment]
**Slack Announcement for Recruitment**

Hello everyone! :wave:

The UI/UX CoP is currently looking for 2-3 UI designers to help us create a logo and a branding guide. [More information can be found here](https://github.com/hackforla/UI-UX/projects/3#card-88582552). If you're interested, please reach out to me directly or reply to this message.

Thank you!
UI/UX CoP co-leads
@ Jennifer Nguyen @ Julia Gab @ Aparna Gopal

**Comment by yychoco91** [comment]
Hi Jennifer,

I would be interested in helping out with this as a UI Designer.

Thank you,
Yrenia

**Comment by nguyen-jenn** [comment]
*Notes*
Slack message on the CoP Leads UI/UX Channel

Monday, March 20th @ 6:13 PM
Hi all! Update: I attended the all teams Design System meeting today. And it seems like Bonnie has asked the design team to create a starter kit so that other projects can use it and then personalize for their own use. I will be attending their design meeting on Thursday to learn more about this and what components they plan to make a template for, to see if it's applicable for the things we need for the CoP.
I think we can still go ahead with recruiting 2-3 designers because even if we have the starter kit, we still need to design a logo as well as choose our colors/typography.
I plan on asking this on Thursday but I also wonder what their timeline for the starter kit is, because if their timeline is months from now, then we may have to just settle for a logo for now, enough for launching the CoP Youtube and wait for the other components at a later time. Just so that we don't create so many things and then have to later on, re-do everything because we have to use the templates they created due to the consistency Bonnie is striving for.
Let me know what you guys think!

Thursday March 23d @ 11:20 AM
Just finished the meeting with the Designers on the Design Systems team!
It seems like they're trying to push out a "design system starter kit" especially meant for new teams that are starting out and struggling to develop their own design system. With this starter kit, it'll have a set of buttons, and some guidance on colors and typography. The information on colors and typography may be useful for our case.
The team also said they will look at old files and see if there's anything useful for us in regards to help create our branding.
