### ISSUE TITLE
Generate Training Modules -  2023-03-22 & 2023-04-12: Sara B & Ying O / TWE Project, ReOps Best Practices

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#427]
### Overview
We need to document the speakers & their workshops. These workshops will function as Training Modules.
- ResearchOps: Knowledge transfer of best practices from the TWE Project to the UI/UX CoP
- Speakers : Sara B & Ying O / TWE Project, attending on 2023-03-22 & 2023-03-12 (Two-part series)
- Keywords: Training, Educating, Upscaling, Upskilling 

### Action Items

PART 1 on 2023-03-22
- [x] Communicate with guest speakers on requirements for knowledge transfer from TWE to UI/UX CoP  
- [x] Make arrangements with guest speakers on dates/timings/types of workshops & walkthroughs covered
- [x] Make announcement on Slack
- [x] Email speakers with consent form 
- [x] Record Workshops by guest speakers 
- [x] Complete knowledge transfer by documenting & making training modules available on UI/UX CoP Wiki

PART 2 on 2023-04-12
- [x] Make announcement on Slack
- [x] Record Workshops by guest speakers 
- [x] Complete knowledge transfer by documenting & making training modules available on UI/UX CoP Wiki

PART 3 on 2023-06-14 [Interactive Workshop - testing ReOps Issue Templates]
- [x] Make announcement on Slack
- [x] Record Workshops by guest speakers 
- [x] Complete knowledge transfer by documenting & making training modules available on UI/UX CoP Wiki

### Resources/Instructions
<details>
<summary>Slack Announcement (edit this)</summary>

:mega: Mark your Calendars! **[GUEST SPEAKER]** will be visiting the UI/UX Community of Practice on **[DATE]**!

:computer: **Topic:** ResearchOps: Knowledge transfer of best practices from the TWE Project to the UI/UX CoP
  
? Please post **your questions** in this [GitHub issue](INSERT LINK) :arrow_left: :arrow_down: 
  
:bust_in_silhouette:**About:** [INSERT BIO] 

:wave: **[LinkedIn or WEBSITE]** [LINKEDIN LINK]

Thank you!
UI/UX CoP co-leads
@ Jennifer Nguyen @ Julia Gab @ Aparna Gopal

</details>

- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- [TWE WIKI](https://github.com/hackforla/internship/wiki)

### Speaker Bio
Sara B & Ying O, as the UX Research Leads, have worked with TWE to set up the Research Ops structure of the project. They collectively have extensive experience that spans years conducting research, research management, data analysis & market research!

**Comment by bradyse** [comment]
### HfLA CoP - TWE Internship
---
### How TWE Internship ResearchOps Started
Presented by @bradyse (former UXR Lead) and @pandanista (UXR Lead)

#### What is the TWE Internship Project?
- [Wiki main page](https://github.com/hackforla/internship/wiki)
- Goals of program
- How UX Research was involved
#### Year 1: IS21 (Spring to Summer 2021)
- Small, highly productive cohort
- One mentor (Bonnie)
- Wanting to improve next year by building out more research plans
- One UXR on project
#### Year 2: IS22 (Fall 2021 to Spring 2022)
- Intense research idea generation occurred before and during internship
- Working at breakneck speed in the few weeks leading up to the internship
- Discovery of consent issues after cohort started ([part of solution](https://github.com/hackforla/internship/wiki/Intern-Research-Plans-and-Goals))
- Working too fast for documentation:
   - [Example messy issue](https://github.com/hackforla/internship/issues/187) (i.e., "How it started")
   - Some documentation processes were at work but work was happening too fast for documentation to occur consistently for all research plans (what the Research Overview Page [looked like initially](https://github.com/hackforla/internship/wiki/Research:-Plans:-by-Number))
- Went from 1 to 10 UXRs
#### Post IS22 (Fall 2022)
- Need for cleaning up research assets (i.e., Wiki, Google Drive, Forms, Spreadsheets, documentation tucked away into comment threads of issues)
- Desire to pause data analysis in order to prioritize documentation 
- Had data for at least 3+ research plans
- Risks of continuing with data analysis without organization:
   - Loss of org knowledge (turnover)
   - Continuing poor documentation processes
   - Non-replicable processes
   - Redoing previous work
- Beginnings of Wiki organization
   - [Current Wiki research overview](https://github.com/hackforla/internship/wiki/Research)
   - [Organize Wiki Page Issue](https://github.com/hackforla/internship/issues/276)
- Need for more UXRs to help
#### TWE ResearchOps (Fall 2023 to Spring 2023)
- [UX Research ad from Oct 2022](https://github.com/hackforla/UI-UX/projects/2#card-86010500)
- General Process:
   - Audit existing documentation in wiki and Google Drive ([example issue](https://github.com/hackforla/internship/issues/284))
   - Create and use issue templates (Click on "[New issue](https://github.com/hackforla/internship/issues/new/choose)")
   - Maintaining [project board](https://github.com/hackforla/internship/projects/1) via issue maintenance
   - Understanding big picture: [Gantt(ish) chart](https://docs.google.com/spreadsheets/d/1EYACJCWPRNp-ybnBuiYwrxMLcW9Lh8BtdVup5h3e9EY/edit#gid=491992055)
- Things to consider:
   - Branding
   - Documentation templates
   - Volunteer access
   - Issue writing: [Example issue template](https://github.com/hackforla/internship/issues/359) (i.e., "How it's going")
   - Issue testing: [Example testing issue](https://github.com/hackforla/internship/issues/335)
#### Next Steps (Spring 2023 and beyond)
- Finish out template building
- Creating a "Research Toolkit" for HfLA Teams
#### How current HfLA Teams can help
   - Learn from TWE Internship mistakes
   - Be up to date with current processes (things are continually changing)
   - Evangelize the importance of ResearchOps
   - Ask current PMs and Leads of TWE Project if okay to use a certain template
   - Use templates with knowledge that the content you're copying may already be out of date

**Comment by pandanista** [comment]
@bradyse I made a few minor edits, but the structure and all the examples look good! 

Copying and pasting the communication on Slack below so we can keep track of the questions we received:
_Could you also please cover super basic level concepts as well, in addition to your planned workshop/talk. We got some of these questions from the Onboarding project, so looks like a lot more folks would be thinking this way too. Questions like:

- How do we name the Folders on the Google Drive? Preferred Nomenclature.
For TWE, since we have lots of research plans and multiple user types, we decided to have one folder called "Research by type", and another one "Research by plan number", which we added shortcuts of the files from the other folder "Research by type". Yours could be different, and it depends on how you would like to structure your research repository.
<img width="400" alt="Screenshot 2023-03-20 at 8 39 02 PM" src="https://user-images.githubusercontent.com/57029070/226513015-2d01b459-d344-4d9e-aa06-3c1284b58c45.png">
<img width="400" alt="Screenshot 2023-03-20 at 8 39 20 PM" src="https://user-images.githubusercontent.com/57029070/226513027-49d6e833-a5ce-4b99-8574-a87eb9a4cac7.png">
<img width="400" alt="Screenshot 2023-03-20 at 8 39 51 PM" src="https://user-images.githubusercontent.com/57029070/226513038-54524f34-16e5-4608-abde-db3c2ee7dc32.png">

For file names , we finally decided on using the following structure: 
TWE: ISYY: RP###: Participant Type (where applicable) + Description of the document 
i.e. <img width="517" alt="Screenshot 2023-03-20 at 8 35 18 PM" src="https://user-images.githubusercontent.com/57029070/226512169-63cc3f02-868d-4e7c-85e7-516eda0bde59.png"> 
[TWE: IS22: RP012: Intern Exit Interview Roll Call and Session Table](https://docs.google.com/spreadsheets/d/14TMOmeYX2yHEyHqttzhq9cDlqeAllcwAa2q33HA-dCQ/edit#gid=1585831764)
For the issue we create to deliver the outcome, we use a similar structure and add an action verb in the end.
TWE: ISYY: RP###: Participant Type (where applicable) + Description of the Research: Action
i.e. [TWE: RP020: Interview Roll Call and Session Table: Create](https://github.com/hackforla/internship/issues/346)
We also had to come up with the naming convention retroactively. [Create Naming Conventions for Research](https://github.com/hackforla/internship/issues/347)

- The Labels on the GitHub Issue: What do all the different labels for UXR templates mean?
Most issues have the following types of labels attached: Size (how long it takes to finish this assignment), Participant Type (who is this for), Feature (what is this issue for or related to), Role (product, research, design, dev, etc).

- Why are the RPs labelled RP001 & not say RP01 or RP1? What is the reason for naming it this way?_

**Comment by Aparna1Gopal** [comment]
**Copy of Slack Message**

:mega: Mark your Calendars! 
[@Sara Brady](https://hackforla.slack.com/team/U0371AXAVUN)
 and 
[@Ying O](https://hackforla.slack.com/team/U03TP1VFALV)
 will be visiting the UI/UX Community of Practice tomorrow!
:computer: Topic: ResearchOps: Knowledge transfer of best practices from the TWE Project to the UI/UX CoP
:bust_in_silhouette:About our speakers: Sara B & Ying O, as the UX Research Leads, have worked with TWE to set up the Research Ops structure of the project. They collectively have extensive experience that spans years conducting research, research management, data analysis & market research!
:question: Please post your questions in the comment section of this [GitHub issue](https://github.com/hackforla/UI-UX/issues/427) :arrow_left:
Thank you!
UI/UX CoP co-leads
at Aparna Gopal at Jennifer Nguyen at Julia Gab

<img width="1061" alt="Screenshot 2023-03-23 at 11 47 47 am" src="https://user-images.githubusercontent.com/86335455/227119869-4964d3c1-79ad-4bca-b3d3-4c2a8d81f689.png">

**Comment by Aparna1Gopal** [comment]
**Copy of Slack Message**

:blob-wave: Thank you all for attending 
at Ying O
 & 
at Sara Brady's training/workshop today! We enjoyed having you all there & the questions that came through!
:spiral_calendar_pad: Sara & Ying will be conducting the second part of this series on April 12, 6PM PST at the UI/UX CoP
:question:Please post any questions you may have in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/427) :arrow_left:
:film_frames: The recording from the training/workshop will be available on our [Wiki](https://github.com/hackforla/UI-UX/wiki/research-ops) soon!

<img width="1066" alt="Screenshot 2023-03-23 at 11 50 25 am" src="https://user-images.githubusercontent.com/86335455/227120318-1eb19d70-e958-449f-b932-ea70e2e5a049.png">

**Comment by Aparna1Gopal** [comment]
**Copy of Slack Message/Announcement on April 10**

<img width="1055" alt="Screenshot 2023-04-11 at 10 19 18 am" src="https://user-images.githubusercontent.com/86335455/231059096-76d1e7de-9e4f-48c1-a563-e07474f6fabc.png">

**Comment by Aparna1Gopal** [comment]
**Consent Form Workshop by Sara & Ying on June 14, 2023** 

https://github.com/hackforla/UI-UX/issues/396#issuecomment-1592172754

<img width="1029" alt="Screenshot 2023-06-21 at 12 07 16 pm" src="https://github.com/hackforla/UI-UX/assets/86335455/02c41b9a-7c50-49f5-b76c-849b8dbf0447">

**Comment by Aparna1Gopal** [comment]
### Notes

- [WIKI](https://github.com/hackforla/UI-UX/wiki/In-house-Speakers-%5Bfrom-HfLA's-UI-UX-CoP%5D) has been updated with all Training Modules & Resources 

- This issue is complete & is being closed

**Comment by Aparna1Gopal** [comment]
### Notes

- [WIKI](https://github.com/hackforla/UI-UX/wiki/In-house-Speakers-%5Bfrom-HfLA's-UI-UX-CoP%5D) has been updated with all Training Modules & Resources 

- This issue is complete & is being closed

**Comment by Aparna1Gopal** [comment]
### IMPACT of Best Practices training & knowledge within the UI/UX CoP
**More teams are starting to adopt these best practices!**

_Slack communication between Civic Tech Job project ReOps Lead & UI/UX CoP Co-Leads_ 

[at] Leah Ellis
Good evening :slightly_smiling_face: I am currently on the Civic Tech Job project and had a few questions for the community of practice leads. I am taken more of an research ops role for my team and want to ensure we are documentation our research proper, we are protecting the privacy of the users, and utilizing more of Hack for LAs best practices when it comes to research. We are gearing up for usability testing with internal members on the organization. Do you have any advise on where to upload our testing videos? for an internal audience is there any guidelines for protecting privacy with Hack for LA? Is consent forms needs for internal members?
[2:45](https://hackforla.slack.com/archives/C05TEJUTJ0K/p1695330915758199)
I can also jump on a quick call to discuss some of these topics further please let me know :slightly_smiling_face:

[at] Julia Gab
Hi Leah!
For uploading test videos you could use google drive (assuming your team has one) and have a “locked” folder or separate drive that only certain ppl have access to. You can also give these ppl limited permission so they don’t invite others in the drive or folder.
Not sure about any specific guidelines for protecting privacy but you could check out HfLA’s code of conduct to make sure?
Are you planning to just store this PII as documentation for your research? I’d say initially you wouldn’t need a consent form unless you plan on sharing any information outside of research, specially if they’re internal members. But depending on how you plan on using this info you could write a consent form (that you can reuse as a template) to let users know the purpose of the research and the data you’re collecting from them so they can agree with it. I guess it’s better to be safe if you have the time to do it :slightly_smiling_face:
Unfortunately I am traveling this week and next so I probably can’t meet on a call atm but happy to continue discussing here and maybe Aparna has other ideas or thoughts as well


[at] Leah Ellis
Thank you for the input. The testing videos may be shared with the UX Designers as well but we have not discussed that. They may observe the testing sessions as well. Do you have a copy of the Code of Conduct that I can view?
[4:01](https://hackforla.slack.com/archives/C05TEJUTJ0K/p1695335513379029)
We really just plan on using it to help the designer better design the platform. We dont have to keep the videos right, we can just write a report? Typically when doing testing like usability testing does each person use there own zoom links if all researchers are leading at different times?


[at] Aparna Gopal
Hi Leah! Second Julia on the points. Adding to it:
- It is better to receive consent from the participants before you interview them. Especially since it is a 1-1 interview, video/audio recording is involved etc. The UI/UX CoP has a consent form template which you can easily replicate/reuse for your own project. https://github.com/hackforla/UI-UX/issues/471 ; New Issue > Guest Speaker Consent > https://github.com/hackforla/UI-UX/issues/new/choose
- All PII related docs including consent forms & interview recordings need to be stored in a 'locked drive.' Contact Admin channel & they can set you up with the same.
- You donot need to keep the videos if the team does not need to. It can be destroyed after the data analysis & report writing. But irrespective of this, all protocols regarding consent forms+locked drive need to be followed. You will also need to mention in the consent forms how your data is going to be collected, handled, stored, deleted/destroyed (i.e the entire end-to-end data collection+storage process)
- For other projects, we have used Hack for LA's Zoom account (to follow best practices). The available+free days/timings on all HfLA Zooms are on 1Password. There is an Excel sheet wherein you can identify the available days/timings. The PMs & Leads of your project would be aware of this Excel sheet & should be able to help you out.
- There is a video submission sheet that projects have used after the video/audio interview. This is a good way to keep track of all the researchers and their respective interviews as they submit them to the locked drive: https://drive.google.com/drive/folders/1eOxxLQoGV6Ca7gEesE2SlG-fHWgRZb-G
- HfLA Code of Conduct: https://www.hackforla.org/code-of-conduct/
- Other training videos within HfLA for best practices in ReOps: https://github.com/hackforla/UI-UX/wiki/In-house-Speakers-%5Bfrom-HfLA's-UI-UX-CoP%5D

[at] Aparna Gopal
Also great to know that you & your team are following best practices in ReOps! Makes my heart full to know that all that the Co-Leads worked for in the past few months is paying off now as more teams start adopting best practices in ReOps:relaxed::hugging_face:. Looking forward to the results from this study at future UI/UX CoP meetings
I am also traveling for the rest of September & will be unable to hop on a call. Happy to continue discussing here as & when I have access. I am also looping in the other Co-Leads to this message thread. They will be able to help you as well, when the rest of us are traveling!

[at] Jennifer Nguyen & [at] Peter Gwon was added to the conversation by Aparna Gopal .
